language: scala

sudo: required

services:
  - docker

git:
  depth: 9999

scala:
  - 2.11.12
  - 2.12.4

jdk:
  - oraclejdk7
  - oraclejdk8

matrix:
  exclude:
  - scala: 2.12.4
    jdk: oraclejdk7
  - scala: 2.11.12
    jdk: oraclejdk8

before_install:
  - export PATH=${PATH}:./vendor/bundle
  # list docker-engine versions
  - sudo apt-cache madison docker-engine
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce

  # reinstall docker-compose at specific version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo sysctl -w vm.max_map_count=262144

script:
  - sudo service docker restart
  - docker-compose up -d
  - sbt coverage "tests/test" coverageReport
  - docker-compose down
  - codecov

install:
  - pip install --user codecov

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

env:
  global:
    - DOCKER_VERSION=1.12.2-0~trusty