language: scala
sudo: required
services:
- docker
git:
  depth: 9999
scala:
- 2.11.12
- 2.12.6
jdk:
- oraclejdk7
- oraclejdk8
matrix:
  exclude:
  - scala: 2.12.6
    jdk: oraclejdk7
  - scala: 2.11.12
    jdk: oraclejdk8
before_install:
- export PATH=${PATH}:./vendor/bundle
- sudo apt-cache madison docker-engine
- sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- sudo chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- sudo sysctl -w vm.max_map_count=262144
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then openssl aes-256-cbc -K $encrypted_f5dd5ea7c332_key
  -iv $encrypted_f5dd5ea7c332_iv -in travis/secrets.tar.enc -out travis/local.secrets.tar
  -d; tar xv -C travis -f travis/secrets.tar; fi
script:
- sudo service docker restart
- docker-compose up -d
- sbt coverage "tests/test" coverageReport
- docker-compose down
- codecov
install:
- pip install --user codecov
- rvm use 2.2.8 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1
cache:
  directories:
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
  fi
env:
  global:
  - DOCKER_VERSION=1.12.2-0~trusty
  - secure: Uu8kuD68TxrzoMZ/9IlP6mkxvzYzobKMHcDNFMSevvReJRPtoreVR53bIUoYPdMzo9+5PFUcTFerStQ5E/HRhZm5OK3YjGwDRXSjShKuxUbVMYHJSdk1t9IORfuGIoC4GwXkW6/lzefYtnpDZ8Vm3sdLXjGLN7rT3jfpPhCZx6wKvPP2dy3om50le/YrIC6gugWMSdp3o6+dPZEOSB77BtrWjacbCyPUZ87xv1aeXgJYbvP6bmhwSjAFV5y6cY5ddXO/dkSZgDda3uzlWZc7uq8XOs7f9rj2UOdweMVm37JE7ejt55dWrG9G8ZHQJwt8jE1SiFnBxWxDBZnX3nsT+L/bqXN6y8rTK37Vo5cO6ipYzjE7o9M+zTUpgQr+71Loemh13imuluxbBq9HH31dbjmFhh3Ob0CSYJgY6hEkcR/H1oFV0EDOoU6J8uqGA/6Md89/BYMNmrjvCeLMeWYNjcmyZeZWZ571h/79pEe0DiSAUyDBtkhXWNf8A+TzrU3EAc9jKMrkje4xY+CpPSUTZAL2K/azUK+tZ8T5IpGLZ7MYD+yf/EwQqba3qFoHGnmP1xySC6TkhrFR2ILaMuB/OYtb+5qpZ+LJpgMJeGvtFvUoUvi3xqBSb1/sK0vKcBsoaghmxSvO0nhVZc6Kv7QZUFsHHuWHLV2L0sJ8xlKSC68=
  - secure: mHGzemnWFDSr5n5pKvj8CP7xfqilip74Lqcp5Wkz6o7lu5hA3Tz6LsJR9SCzuDxnRNmXq2L4SabPWS3KegzpjwWUS5hvoepFLjIpjj2NWj8mvN7e0QhWs3K/eV9XoYGu2dJbI9tnnjeuq0oVftLvAH1BLb9Y12G9+RhIcMIE0MxM7ZoafnsJt6hmSBAM1W4nEcFrFXj5jYUjurLI3dSuSvtqONQJpZi0vsYgIAzfDOEY1svc8PevRris7nuGMEQe8m7Mb36xDFn96/uwZeCwbnbhiu0tFNcmVRl/r1Ah2Hued3jcypJ2oGxrl5sRXU+nfShCRvFtGEg0DsgWB+H8UiClwEs7pgY/BZPGN6wL6hlWJohuFXgODjpKoYDKZSGFNmMU/7S4mAil7SGi+Tu6JbT+/U3O7q0fcH5lWEZ7igvQLvQs6y4l5fd4y82Na1u35zDH7FgOEDw89j15z8RCi525lTLjh0naGUBhSlecYqE8yuc773ngfG6jUoPfVVQMw4EF9nfL7xBUssHJyYxklEZxwTbn8UXSmMZhuSKfpjyTofcunAoLJkeVU1JYhwu1iMaJJnnNVRdFl/rkqN2xtMvpYQpLeKhMRE0I3BIhhrKfctXyCffOgrvAOB6sDVmrlN/W3jeRHkojQGz4ZzNSQBRfQMJG+00GIXjV43ZIBq0=
  - secure: LeRCq0OJqxQpff04MkOugmohPavDWSxEepwxWz5GT1IaOHcunBltf49E2CCDLbo4QzXhSDHhFrtTDa/YFkXG+wrhO9dOZbbdLf2fpCbndDVvAscl/qRV1HwkK9Gwr21N+cSgrTszZwGbi/EfMEhtsnh4xCktM2ppZBw1NTTiwzFYLpSgl28ZNu1pqh3RpEX4p74EbWVsE+P5dF46sdSYwYjvceTlRPW8bmyNZbEoQF6O+kIE3MvynvCngcJvOvcCYWVf6PWkUjf5kF8qX7FZpECg/f4lzIfHI54dBTrdtkSwFua+PUMmo5w0xg/e/ajpvEs9K6aKl/9/Ixj8SCQlNlg/9Gk5w/7LKE4OAwx77N4p3Pz+3g9MyTEmcnW2a+IsIckK9LV7XzJnLNbYVi14ah5qLxWeQwwIq2HEXkERkAgeiXvvEBaVB1y2sIApu5a8cDnRr+r629byPh+voyRyE8HzQGltA97nALxtPb59BplOXAo6K0u4nRKmgH4JEGnVXSDYFYv7APFem4bZLoyJJ2wsTK8S3jLPjcLVlvLhZi1h5Gb+n2D5fTsCaMueAVETOg6j6NVZem200dMaFdm/aqGE9JoaPrwnVC1zVCUbtoFRhs1+D5KY2WCcVgEBlG7VMXN/DFRV1HElKTen9Ro7Q2ozwgG2WKH5hpB9KdQ9Efc=
